# change the followings to match your Github username and repo name
baseurl: "/" # the name of your github repo
url: "https://seheinzel.github.io" # the url of your github pages

# site information used in page title, meta data etc.
title: "Stuff to see, amazing and tedious"
description: Data Science?  More like Sally Science.

# color theme for links
theme-color: green # indigo|yellow|pink|green|stone|

# homepage information
author: Sally Heinzel
author-bio: House of the Rising Henzel   # change to false to hide
author-image: heinzel_in_goggles.jpg  # file must be in the /assets/img/ folder

# navigation menu
show-nav-menu: true

nav-menu:
- text: About
  permalink: about
- text: Code
  permalink: code

# use false to turn off any social media links
twitter: false
facebook: false
instagram: false
github: https://github.com/seheinzel
linkedin: false
medium: false
google-scholar: false
email: false

# footer information
footer-msg: "Powered by HTML, DNS, and 🐙"
# footer-msg-link: false

# google analytics
# google-analytics: G-WCRC1TC2V5

# jekyll plugins - no need to change
plugins:
    - jekyll-seo-tag
