# change the followings to match your Github username and repo name
baseurl: "" # the name of your github repo
url: "https://seheinzel.github.io" # the url of your github pages

# site information used in page title, meta data etc.
title: "Sally Heinzel's Portfolio"
description: Data Science?  More like Sally Science.

# color theme for links
theme-color: pink # indigo|yellow|pink|green|stone|

# homepage information
author: Sally Heinzel
author-bio: Hi, I'm Sally. Thanks for checking out my portfolio. Above you'll find links to different types of work I've done. I'm an early career data analyst with a passion for data wrangling 🤠 in order to allow data to live its best life. I also enjoy problem solving and the endorphin hit that comes with debugging a particularly stubborn challenge. Feel free to [reach out](mailto:sallyeheinzel@gmail.com) to me if you have any questions or comments.    # change to false to hide
author-image: profilepic.JPG  # file must be in the /assets/img/ folder

# navigation menu
show-nav-menu: true

nav-menu:
- text: Home
- text: Resume
  permalink: resume
- text: Code
  permalink: code
- text: Projects
  permalink: projects
- text: Writing
  permalink: writing
- text: Reports
  permalink: reports

# use false to turn off any social media links
twitter: false
facebook: false
instagram: false
github: https://github.com/seheinzel
linkedin: false
medium: false
google-scholar: false
email: false

# footer information
footer-msg: "Powered by HTML, DNS, and 🐙"
# footer-msg-link: false

# google analytics
# google-analytics: G-WCRC1TC2V5

# jekyll plugins - no need to change
plugins:
    - jekyll-postcss-v2
    - jekyll-seo-tag

theme: jekyll-theme-cayman